### PR TITLE
Add additional prefixes and change reglementaire bijlage uri

### PR DESCRIPTION
**Pull request by elpoelma**
This PR introduces two new things:
- The `say` and `dossier` prefixes are added to the defaultContext.
- The URI of a reglementaire bijlage is changed to `dossier:Stuk`. This should probably still be changed to be a subclass of `dossier:Stuk`, more specific to reglementaire bijlagen.

### CODE REVIEW

**Review by abeforgit — CHANGES_REQUESTED** [review]
The dossier prefix is not defined before it is used in the html, rendering this invalid rdfa
you can see this by putting the html of a new template into rdfa.info/play

**Comment by abeforgit** [comment]
same problem, lblodgn prefix is not defined in the html

**Comment by elpoelma** [comment]
> same problem, lblodgn prefix is not defined in the html

Will look into it.

**Comment by elpoelma** [comment]
> same problem, lblodgn prefix is not defined in the html

It seems to be valid for me.

**Comment by elpoelma** [comment]
I added the lblodgn:ReglementaireBijlage class in a migration to https://github.com/lblod/app-centrale-vindplaats/pull/20.

**Review by abeforgit — APPROVED** [review]
sorry my bad, false positive

**Pull request merged**
