### PR TITLE
Add search to the snippet management page

### PR DESCRIPTION
**Pull request by lagartoverde**
## Overview
Added a search field on the snippet list page

##### connected issues and PRs:
GN-4936

### Setup
None

### How to test/reproduce
Go to the snippet list page and you should be able to search by label

### Challenges/uncertainties
None

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by elpoelma — APPROVED** [review]
Works as expected.

**Comment by elpoelma** [comment]
@lagartoverde can we merge this one?

**Comment by piemonkey** [comment]
> yes, it's failing on dependency lint, I guess it's not important, wanted to ask but I forgot

It's weird that it's not failing on master. Maybe it needs to have master merged into this branch to make sure it's running on the correct package.json?

**Comment by elpoelma** [comment]
> > yes, it's failing on dependency lint, I guess it's not important, wanted to ask but I forgot
> 
> It's weird that it's not failing on master. Maybe it needs to have master merged into this branch to make sure it's running on the correct package.json?

It also fails on master locally on my side. I think after we merge the dependency-bump PR, it will be alright.

**Pull request merged**
