### PR TITLE
Feature/add insert variable plugin

### PR DESCRIPTION
**Pull request by lagartoverde**

### CODE REVIEW

**Review by abeforgit — COMMENTED** [review]
Can't insert a codelist that I just added in the backend, not sure if I'm doing something wrong in testing

EDIT: this is a caching issue, did show up after a restart of the FE

**Review by elpoelma — CHANGES_REQUESTED** [review]
Inserting variables into a template works well overall. I cant seem to insert a codelist because there aren't shown any. Some translations are still missing like insert.variable .

**Comment by lagartoverde** [comment]
Do you have codelists any codelists on the organization you are testing with?

**Comment by elpoelma** [comment]
> Do you have codelists any codelists on the organization you are testing with?

Yes I did. But when testing a second time it did work as expected.

**Comment by lagartoverde** [comment]
> > Do you have codelists any codelists on the organization you are testing with?
> 
> Yes I did. But when testing a second time it did work as expected.

Weird, it could be the cache

**Comment by abeforgit** [comment]
This pr is completely broken and would set back the master branch by quite a lot if merged
please consider the sanity of your reviewers
superseded by #18

**Pull request closed without merging**
