### PR TITLE
GN-4330: allow single/multiselect specification per codelist instance

### PR DESCRIPTION
**Pull request by abeforgit**
-------

## Overview

Updates the plugins so it can use the new codelist single/multi select option
also removes those options from the codelist management page.

No other changes were needed cause everything is backwards compatible
(if a codelist has no explicit style, the backend will be polled).

##### connected issues and PRs:

[GN-4330](https://binnenland.atlassian.net/browse/GN-4330)
[backend pr](https://github.com/lblod/app-reglementaire-bijlage/pull/68)
### How to test/reproduce

make codelist with qa env, proxy this pr to qa env, verify everything still works
optionally add `<VariablePlugin::Codelist::Edit @controller={{this.editor}}/>` to
`app/templates/regulatory-attachments/edit.hbs` temporarily to verify the option select is working
as intended, or use GN.
### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by x-m-el — CHANGES_REQUESTED** [review]
It still shows single/multi select in the codelist overview page (/codelists-management). Will have to be removed there too.

`codelist-type-select-option` css is still present but not needed anymore.

Database does now have "legacy" data just to make old documents (that didn't specify inside document) work. Which is fine, better than to break stuff or have a big query.
Could have also approached this by still allowing the setting of the codelist here, but changing the name to the "default type". Then when inserting a codelist in a document, this default type would be selected by default.
But that could also be confusing so I'm totally following your approach :)


Beside that, I don't think the type is still needed in the model and resources (in app-repo)? Either I'd remove those, or add a comment why they are not added anymore, but might still exist for old codelists.
Adding a comment to the codelist-type in the model file will also have the advantage that there will be some *added* code, which will directly link to this PR with a decent explanation (and links) of what changed and why the legacy data is present.

**Comment by abeforgit** [comment]
good catches, thanks @x-m-el !
Yes I considered going the default route, but figured that was too complex for something where I suspect the 99% majority of cases will be single selects anyway (multi-selects insert all their selected values as a comma-separated list, which is sensible, but I don't see too many usecases for that in a human-readable text)

also true about the backend, I'll remove the properties from the resources config there. I'll keep the data (though realistically there is no data yet on prod).
I'm conflicted about that though, this drift between the implicit data "api" and the actual content is something I'm not sure how to deal with (in this case it has no impact, but still)

**Comment by x-m-el** [comment]
> also true about the backend, I'll remove the properties from the resources config there. I'll keep the data (though realistically there is no data yet on prod).

I guess MOW does have  `multi/single select type` data  for codelists on prod already though. (MOW should get a similar change as this?).
If this was really only QA I'd almost say to just break those codelists (=choose default of single select) and avoid the problems all together. But MOW is the main reason this backwards compatibility is needed I think?

The "real issue" is that this should probably be a migration, but that's a lot more work and more chance to bug out, so I 100% agree to not do that approach :)


And yes, it's not the first time mu-cl-resources gives me a confusion of how to interpret it. Is it our API, or is it a view of what the database has?
Really it makes more sense as pure API (containing only what we need from the api).
But database structure is so closely (100%...) related to what is defined in mu-cl-resources, the distinction is really blurry, especially since it kinda is the *only* decent view of what the database contains. It's both our API definition as our "database scheme" (the only place that can have extra info about the database scheme too).

**Comment by abeforgit** [comment]
yeah resources is decidedly not 100% of the api, but its the only place any sort of database schema is actually defined, so we often look to it as our source of truth
This is quite a fundamental issue with our stack that has had multiple rounds of discussion pass over it already, but it's slow moving of course

**Comment by abeforgit** [comment]
yeah for MOW I suppose we should keep the codelists as-is for now, that app has such a different interaction pattern that im not sure how to tackle it

**Pull request merged**
